### ISSUE TITLE
Refresh purpose.md for Clarity and Structure

### ISSUE THREAD

**Issue by logtay** [paulrosen/abcjs#1019]
Hello! I searched for similar issues and didn't see anything.

The Purpose page of the documentation is often one of the first that new users and potential contributors will encounter. I feel it could benefit from some enhancement to improve its clarity, structure, and readability. I have been enjoying experiementing with this library and feel these changes could make it even better for newcomers. 

**How can it be improved?**
-Detail and Minor Revisions: Adding more detail/revising some content and bullet points could make the page more informative for new users.
-Restructure Sections: Section headings could be structured to better improve clarity. For example: “Key Features”, “Limitations”, “Open Source Applications (No programming required)”, “Browser and Device Support”.

**Comment by paulrosen** [comment]
I'm too close to the project to realize what new people don't know. To me the section seems fairly clear as it is. I don't want to put too much detail there because I am trying for an overview - that page should simply answer the question about whether this library is appropriate for the user's needs.

If you have a question about the purpose of abcjs please ask it here and I'll answer it in that file.

If you have a suggested sentence or two to add, please suggest it here, too.
