### ISSUE TITLE
listener to return current midi note

### ISSUE THREAD

**Issue by desafinadude** [paulrosen/abcjs#130]
Hi

I'm trying to return the current note playing...

I'm using:

```
midi_options: {
	generateInline: true,
	generateDownload: false,
	listener: midiNote
},
```

but the midiNote function returns a div not the note:

`<div class="abcjs-inline-midi abcjs-midi-0 abcjs-midi-current"></div>`

How can I get the note name being played?

Thanks in advance

**Comment by paulrosen** [comment]
First, let me apologize for the confusing sets of parameters. I'm planning on addressing that in the next version.

Second, there is not currently a way to easily get the note name, but there is enough information to figure it out. I also plan on addressing this in the next version.

I'm in the process of creating a simple tool that makes it easier to visualize what the parameters do. It is: https://configurator.abcjs.net/audio/ If you go there, you will notice two different callback options "Listener" and "Animate". Choose one OR the other to see the effects. "Listener" is more time based and is useful for a progress bar. "Animate" is event based and is useful for "bouncing ball" effects.

What data are you specifically interested in? Just the current note information, or where that note is in the whole tune? That is, would you want the start and end characters pointing back to the string or just the actual pitch? Do you want the note that is displayed to the user or the sounding pitch (taking transpose and the key signature into account)?

**Comment by desafinadude** [comment]
Hi Paul

Thanks for getting back to me. No apology needed - great work you're doing ;-)
I would like to get the sounding pitch so that I can visually illustrate that. 
I will have a look at the configurator above as well.

I am using it in the context of ABCJS.Editor btw - not sure if that changes the way one access the MIDI events.

Thanks so much - and again - great work.

**Comment by paulrosen** [comment]
The editor, versus the renderAbc function doesn't make any difference in this case.

Let me see what I can do.

**Comment by desafinadude** [comment]
Thanks Paul :-)

**Comment by paulrosen** [comment]
The next version (v3.3.3) will have extra parameters passed to the callback:
```
animateCallback(lastRange, currentRange, context) {
    var startChar = currentRange.startChar;
    var endChar = currentRange.endChar;

    // Assuming the original string you passed in is call abcString
    var currentSource = abcString.substring(startChar, endChar);
}
```

**Comment by paulrosen** [comment]
That is probably correct: do those items, in fact, represent notes in your file?

What is the ideal format for you for the returned notes?

**Comment by macno** [comment]
In my scenario the ideal would be to receive only the note played.
In my file for example I see: `| z (c e2) |`, it would be perfect if I was able to receive only `c` and `e2`.

Another solution could be to add a new listener that will be invoked when a note is played.
If you think it's possible, I'd be happy to implement it and open a PR, but in this case I'd need some hints from you on where to look at.

**Comment by paulrosen** [comment]
If you upload the abc file I'll look at it. It should have just been the note played. I will be releasing some bug fixes at the end of the year.

**Comment by macno** [comment]
This is the abc file, it's been generated using xml2abc 

```
X:1
T:越後獅子
L:1/8
Q:1/4=92
M:2/4
I:linebreak $
K:C
V:1
"^Allegro"!f! AABA | BABc | ecBA | F3 z | FABA | F3 E |$ FAFE | DDDE |!f! FEB,D | E3 z | %10
!mf! D D2 E | F F2 E |$ AABA | B2 ce | ^f f2 e | ccce | ^f f2 e | ce/c/ BA |$ BceA | cBAF | E3 F | %21
 AB c2 | e2 cB | A2 AF |$ A3 B | cBAF | E3 E | BccB | cecB | ABcA |$ FA/F/ ED | EF A/A/A/A/ | %32
 BB cc/c/ | Bc/B/ AB/A/ | FEDD |$ z EFA | FE B,B,/B,/ | B,D E2 | z (c e2) | cBAB | (cA) F2 |$ %41
 EDEA | F3 E | FF/F/ ED | DE z (B/>A/ | F2) (F2 | E2) z2 |] %47
```

thanks

**Comment by paulrosen** [comment]
For the measure that you mentioned, I see the following returned:
```
  " z "
  "(c "
  "e2) "
```
This seems correct to me - what you are seeing is the original string that created that midi event.

However, I see what you mean, that you'd like to have the midi event instead of the ABC. I'll see what I can do.

**Comment by andrewhannum** [comment]
Hi Paul - I'm curious if this issue was ever addressed as a result of a refactor?

The ABC text substring gets me pretty close for easy tunes, but it falls short when dealing with accidentals in the key signature, and even worse accidentals that occur multiple times in a single measure. (for example, a note is sharped once at the beginning of a measure, and then written later without the sharp, but it still understood to be sharp).

I just realized as I was typing this that I had emailed you about this same request almost exactly a year ago! - I'm the one trying to build a sight-reading trainer using pitch detection. I don't mean to nag, I promise! Just curious if including the midi info might be any easier now due to changes. If not, I'll just keep moving ahead.

Thanks for all your work and help.

**Comment by paulrosen** [comment]
I'm pretty close - I will have a much improved midi system soon. The current "master" branch already has some improvements. If you can run that, try doing callbacks with TimingCallbacks instead of the midi callbacks. If that format is more usable to you, then in the short run you could start that at the same time you start the midi. As soon as I get some free hours I'll have an improved midi system that using those callbacks.

And if there is something you still need that you don't get with TimingCallbacks let me know. This is the time that I can improve that.

**Comment by paulrosen** [comment]
I think the new audio system doesn't have this issue. Let me know if there is still a problem.

**Comment by kwertyops** [comment]
Hi @paulrosen - I've finally gotten a chance to try out the new timing callbacks system. It looks like it should give back what we need, but the event callbacks always contain an empty array for the 'midiPitches' entry.

I would think that I'm doing something wrong, except the same is true of the timingCallbacks example on your documentation page! (https://paulrosen.github.io/abcjs/animation/timing-callbacks.html#example)

When you run the timer, the output shows all of the midiPitches arrays as empty on the event callback, when they definitely shouldn't be.

Am I missing something about how to correctly use this new system?

**Comment by paulrosen** [comment]
All you are missing is the latest code that I just wrote this Sunday! I plan to wrap that into a release very soon so you should look for version 6.0.0-beta.10
