### ISSUE TITLE
Separate note head class from stem

### ISSUE THREAD

**Issue by RCJacH** [paulrosen/abcjs#192]
Is it possible to have an individual class for note heads, so we can do coloring and hiding (showing the stem only) without affecting the stem?

**Comment by paulrosen** [comment]
I can see how that would be useful.

However, that is not an easy task at the moment. If you inspect the SVG you'll see that the various parts of a note are combined into a single `<path>` to cut down on the number of individual elements that are on the page.

(I don't know how true it still is, but a number of years ago I did some performance testing and saw that the biggest factor in bogging down the browser was the total number of elements on a page.)

**Comment by jaredly** [comment]
I would also like something like this -- I want to be able to style the different notes in a chord differently, but as you say they are currently rendered as a single path.
I think it would probably make sense to have it be a configuration option passed in to the renderer, so that people who don't need that functionality can get the performance benefits of having fewer nodes.

**Comment by joshstovall** [comment]
Agreed, this would be a great addition. 
Regardless this library is amazing! Thank you.

**Comment by paulrosen** [comment]
fixed
