### ISSUE TITLE
Export SVG without adding to DOM

### ISSUE THREAD

**Issue by mididev** [paulrosen/abcjs#201]
Hi,

I'm sorry if I'm totally wrong here with this topic but I'm pretty new on github. Please let me know if there's a better place for that.

I'm developing a notation tool using FabricJS. I want to insert different tiny pieces of abcjs notation into the FabricJS canvas. As FabricJS can embed SVG I can render ABC into a div and grab the result via querySelector("#notation").innerHTML but this feels very hacky.

    <div style="visibility: hidden; width: 1px; height: 1px; overflow: hidden">
        <div id="notation"></div>
    </div>

    function getSvgForRhythm(abcRhythm, scale, width) {
        var abc = 'X:1\n' +
            '    L:1/16\n' +
            '    V:ALL stem=up\n' +
            '    K:C treble style=rhythm clef=none stafflines=0\n' +
            '    %%musicspace 0\n' +
        abcRhythm;

        ABCJS.renderAbc('notation', abc, {}, {
            add_classes: true,
            staffwidth: width,
            scale: scale,
            paddingtop: 0,
            paddingleft: 0,
            paddingright: 0,
            paddingbottom: 0
        });

        return document.querySelector("#notation").innerHTML;
    }

    var canvas = new fabric.Canvas('c', {
        width: 1000,
        height: 600,
        selection: false
    });

    for (const part of parts) {
        const svg = getSvgForRhythm(part.rhythm, 1, cellWidth);
        fabric.loadSVGFromString(svg, function(objects, options) {
            const obj = fabric.util.groupSVGElements(objects, options);
            canvas.add(obj);
        });
        [...]
    }
}

I really would prefer getting the SVG string without having to use a div that I have to hide via CSS. Is there a way to archive that? And if not, would it be very hard to add such a function into abcjs? I can imagine that it's not only that it feels better to avoid the div but also has some performance benefits because adding elements to the DOM slows down the rendering...?

I'm very grateful for any tip.

Best, Lukas

**Comment by paulrosen** [comment]
I've been thinking about doing a small change to make touching the DOM the absolute last step, in which case it would be possible to construct an SVG string instead of constructing SVG elements. There is one stumbling block: whenever there is text, I figure out how much room the text takes up by writing it to the DOM and measuring it. That way I take into account all things that might affect it, like outside CSS. I'm not sure how to figure out the size of text otherwise.

If you are doing small amounts of ABC notation I don't think performance will be an issue - I agree that writing to the DOM is the slowest part, but it is still pretty fast, at least for a single page worth of music.

I think how you're doing it gets the job done and is maintainable. I can't imagine a change I'd make to the library that would break it.

**Comment by mididev** [comment]
Thanks for your answer Paul!

Okay, I will stay with my solution for now. Good to hear it's not the worst approach to do it :-)

I see, sounds not that trivial to avoid creating the DOM elements when it comes to measuring the text (I've been also struggling with getting text sizes myself and wondered if there's an easier way to do it)...
