### ISSUE TITLE
Does abcjs support midi2abc?

### ISSUE THREAD

**Issue by Kreijstal** [paulrosen/abcjs#204]
If it doesn't, what would it be necessary for it to be merged if someone made a pull request implementing it?

I know it is not an easy thing. But [it has already been done although in C](https://github.com/leesavide/abcmidi)

I was thinking of using abcjs to make a GUI web-based abc editor where you can edit the notes through the GUI, but of course it would be easier to convert these from MIDI.

**Comment by paulrosen** [comment]
It doesn't exist, but it would be great if it did. 

MIDI doesn't quite have the same info as written notation - for instance differentiating between C# and Db as an easy example. And you'd have to decide how exact you wanted to get it. Do you notate every small change in volume with dynamic marks?

It's a different problem to create a GUI - that is probably easier. It would take some work making the GUI, but the ABC notation mirrors the way the notes look on the page. The problem there is that there is more than one way to write ABC. If you didn't care whether something was `A>B` vs. `A3/2B/2` it is ok. And you'd lose any comments if you imported a file then wrote it out.

For merging it, I'd be happy to. I'd probably want it to be a separate module (like MIDI is now) unless the code was particularly small, because I wouldn't want everyone to have to load that code if they weren't creating an editor.

If you use abcjs to render the string, then put a bunch of event handlers in the resulting SVG, you can do the modifying of the string in your own code, and have abcjs rewriting as you go. 

You could basically use the editor - keep a (perhaps hidden) textarea with the latest string and the SVG will update automatically.

When you get that working, if you want to contribute it, write to me - the only fast requirement is that it be ES5 code - I want to be conservative about dropping support for old browsers.

**Comment by paulrosen** [comment]
closed for lack of activity
