### ISSUE TITLE
transpose selection

### ISSUE THREAD

**Issue by ThorsenRune** [paulrosen/abcjs#215]
Hi, I look for ways to: make a selection of ABC source and transpose a number of semitones.
Should I make a simple search replace  or is it possible to hook into a parser? 
Currently I try to figure out how to and if ABC2ABC could be used?
What do you advice?

**Comment by paulrosen** [comment]
abcjs will transpose source ABC strings for displaying in a different key and/or for playing in a different key.

However, it won't spit out a new ABC string in the new key. ABC2ABC is definitely the tool to use for that. That doesn't run in the browser, though, so you'd have to do that part on the server.

**Comment by paulrosen** [comment]
Is this what you want?
```
X: 1
T: transpose-clarinet
M: 2/4
L: 1/4
V: Vi name="Violin"
V: Cl name="Clarinet" score=_B
V: Tr name="Trombone" clef=bass
K: Emin
V: Vi
"Em"EF|]
V: Cl
"Em"EF|]
V: Tr
"Em"E,F,|]
```

**Comment by ThorsenRune** [comment]
Grand, so that was the hidden gem ;-). Very nice. So for future reference you can write a clarinet staff in the score like this
V:V1 clef=treble name="Bb instr"   score=_B transpose=-2 	
I see that a subset is possible: _B _E but not A and D.
I would propose to let the keyword be the more intuitive ‘transpose’ in addition to ‘score’ and let transpose work on both midi and visual layout.
I can see it implemented in abc_parse_key_voice.js 
as : function () :addNextNoteTokenToVoiceInfo
Currently handles only arguments
	var noteToTransposition = {
				"_B": 2,
				"_E": 9,
				"_b": -10,
				"_e": -3
			};

P.S. Do you have these ‘tricks’ written up somewhere? I couldn’t find score as in the ABC notation ‘standard’

**Comment by ThorsenRune** [comment]
For those interested: I went into abc_parse_key_voice.js 
 and added some lines that sets 
multilineVars.voices[id].scoreTranspose=-multilineVars.voices[id].transpose
so for example 
V:Cl name="Clarinet"  clef=treble middle=B transpose=-4
will transpose a A Clarinet
in that way transpose will do a complete transpose both visual and midi, as I would intuitively expect
I implemented the workaround here: https://github.com/ThorsenRune/abcjs/blob/master/src/parse/abc_parse_key_voice.js
in case you like to merge it.

**Comment by ThorsenRune** [comment]
Hi, when working on a score I found it useful to be able to transpose a selection of the 'source' (not the visual score). Until now Ive resorted to copying pasting to other websites (like mandolintab)
It would be nice to be able to select a voice and transpose it up or down some semitones.
So far Ive found out that EngraverController.prototype.rangeHighlight can be hacked to get the selected elements after : 'elems[elem].highlight()'
like adding a global variable like: SelElem.push(elems[elem])
Then I can run through SelElem which contains positions of the abc text. Right now my simple solution is to just replace nodenames but my accidentals gets lost. 
Is there a solution already or are anybody interested?

**Comment by paulrosen** [comment]
I think what you are asking for is a way to output a new ABC string that contains the transposition, right? That is, if you input the string that contains the notes`cdef` and you request "transposition down two half steps", then you want the string `Bcde` returned. Is that correct?

And you are requesting that for a selection of the string instead of the entire string? Or perhaps for a single voice?

As a general solution - this is more difficult than it seems because there are lots of ways to express notes in ABC. However, it would definitely be useful.

(It's especially useful if you have a tune but the singer wants a different key.)

Let me think about it and see what I can do - I would probably want to start by having it transpose the entire string instead of a selection. 

There is a question about what to do with the key signature if you transpose a selection. Do you want to insert a `[K:Bb]` at the spot where you are transposing, then `[K:C]` at the end of it?

**Comment by ThorsenRune** [comment]
What I have come up with is a simple loop through the selected elements which have the character positions. Then I shift the letters by an interval, called by alt+arrow up/down.
It does not take into account the tonality but I use it for quickly  transposing parts of voices. The code is a hack so I have to clean it up if you are interested.  It would be good to be able to choose between cromatic and diatonic tranposition, though but the algorithm is not clear to me yet.
