### ISSUE TITLE
 I want to edit and re-render a tune object.

### ISSUE THREAD

**Issue by ApplePedlar** [paulrosen/abcjs#260]
I want to edit and re-render a tune object.
But I can not because renderEachLineSeparately is private method.
Please publish renderEachLineSeparately method.

Assume the following code:
```
let tune = abcjs.renderAbc("abc", this.$refs.abcInput.value)[0]
let transformer = new KeyTransformer()
transformer.transform(tune, this.keyOffset)
abcjs.renderEachLineSeparately(this.$refs.abcObj2, tune, {}, 0)
```

**Comment by ApplePedlar** [comment]
I am creating a score creation tool for harmonica.
I want to display the numbers corresponding to the pitch as lyrics.
So I want to get pitch information from tune object, embed lyrics and display it.

**Comment by paulrosen** [comment]
Rerendering the entire piece instead of just one line is pretty quick - can't you just make the modifications to the ABC string, and just call `renderAbc` again? I might not be understanding the entire use case.

Also, do you need to render the lines separately? That is normally done when you want to insert non-abcjs material between each line. It sounds like you are adding a `w:` line so you don't need it. (Unless I misunderstood "embed lyrics".)

And, if you do want to use `renderEachLineSeparately`, you specify it as a parameter: `abcjs.renderAbc("abc", this.$refs.abcInput.value, {oneSvgPerLine: true})`

Does this answer your question? I might not be accurately visualizing what you are doing.

**Comment by ApplePedlar** [comment]
I don't want to modify ABC text. Because doing that automatically requires complex string processing.

If the tune object can be modified and re-rendered, it can be implemented simply.

The ideal is that I can simply create a tune object and then pass it to the render method for rendering.

**Comment by ApplePedlar** [comment]
This is my project that using forked abcjs.

https://github.com/ApplePedlar/chsm
https://applepedlar.github.io/chsm/

**Comment by paulrosen** [comment]
I got a chance to look at the project. That's pretty cool!

I think what I would want for this project is a hook. If I added a callback right after parsing, I think it would do exactly what you want:

```
      let configure = {
        responsive: "resize",
	after_parse: this.addHarmonicaScore,
        format: {
            annotationfont: "Times New Roman",
        }
      }
      let tune = abcjs.renderAbc("abc", this.$refs.abcInput.value, configure)[0]
      abcHarmonicaScoreMaker.addUnderline(this.$refs.abcObj)
```
Then:
```
addHarmonicaScore(tuneObj) {
      let abcHarmonicaScoreMaker = new AbcHarmonicaScoreMaker()
      abcHarmonicaScoreMaker.transform(tuneObj, Number(this.offsetPitch))
}
```
You wouldn't need to draw the music twice; you wouldn't need to have separate SVG for each line; you wouldn't need a second div for drawing into.

**Comment by paulrosen** [comment]
I'm definitely adding this hook and I should have it released in a day or two. I will send you a pull request to show you how to use it then.
