### ISSUE TITLE
REACT-NATIVE    : :    ReferenceError: Can't find variable: Element  

### ISSUE THREAD

**Issue by insomniac807** [paulrosen/abcjs#276]
```javascript
import abcjs from 'abcjs/midi';

export default class MusicScore extends Component {
    constructor(props) {
        super(props);
        this.state={
            data: this.props.navigation.getParam('abctune'),
        }
    }
    render(){
        data = this.state.data;
        renderScore = () => {
            abcjs.renderAbc('notation', data);
        }
        return(
            <WebView 
                source={
                    {html: `
                        <!DOCTYPE html>
                        <html lang="en">
                        <head>
                            <meta charset="UTF-8">
                            <meta name="viewport" content="width=device-width, initial-scale=1.0">
                            <title>Document</title>
                        </head>
                        <body>
                            <div id="notation"></div>
                        </body>
                        </html>
                    `}
                }
                domStorageEnabled
                javaScriptEnabled
                injectJavaScript={renderScore}
            />
        );
    }
}
```

The code above produces the following output

[https://i.imgur.com/rnYOgOX.png](url)

dev enviornment:
    OS: Windows 10
    node: v12.10.0
    Android Studio: 3.5.2

installed via package manager:
   npm install --save abcjs

**Comment by paulrosen** [comment]
I haven't used React Native, so this is a quick guess: does this get called before the DOM exists? When using other SSR rendering frameworks, one has to use `require` after the window exists instead of using `import` at the top.

I'd be happy to try to duplicate your environment if the above wasn't enough of a clue.

**Comment by insomniac807** [comment]
> I haven't used React Native, so this is a quick guess: does this get called before the DOM exists? When using other SSR rendering frameworks, one has to use `require` after the window exists instead of using `import` at the top.
> 
> I'd be happy to try to duplicate your environment if the above wasn't enough of a clue.

Nah, react-native doesnt use a DOM as its native mobile technology, But if this were react, the DOM gets created, then react bundles all the components together and adds the final stack to the DOM. So all code would run after DOM creation. 

I'm only learning react-native myself so I'm not sure exactly how this is handled on android or ios. 

My setup is

OS: win10
Node: v12.10.0
React-Native: 3.0.0-alpha.7
Android Studio: 3.5.2 running android pie (pie = requirement for react-native)

and installed abcjs from node. 

(just looking at it now actually, the issue might be with the js Element object in abc_common.js not being recognised by mobile technologies. There is a react-native version of abcjs, I'm assuming you don't have anything to do with that though? There isn't any documentation available for it)

**Comment by paulrosen** [comment]
I looked at this a little more - I can get past that problem, but you would hit another problem a little later. I need an instance of an SVG to figure out spacing so at some point you definitely need a DOM.

What happens if you move the `import abcjs from 'abcjs/midi';` to here:
```
render(){
  const abcjs = require('abcjs/midi');
```

**Comment by insomniac807** [comment]
I will try that and get back to you. My solution at the moment is to create a html template file with the js code and run it in an embeded browser

**Comment by Swinkid** [comment]
Any update on this issue?

**Comment by paulrosen** [comment]
I have gotten SSR to work by doing the trick I mentioned on Dec 5. You just can't reference abcjs until the DOM is present, though. I need the DOM to be able to calculate the sizes of the various elements - partly because it depends on CSS.

**Comment by paulrosen** [comment]
Closed for inactivity. If there is still a problem please reopen.

**Comment by rpattcorner** [comment]
Reopening.  I'd very much like to consume a react-native capable implementation in a mobile app I'm building for musicians, but from this thread it sounds like that's a blind alley because a DOM needs to be present for the render-to-image (or to sound probably), and react-native does not use a DOM that I know of, just native components.

@paulrosen is this your understanding, or did the Jan 4, 2020 comment indicate an end-to-end success with rendering?

There's a [react-native-songbook](https://github.com/MatthewDorner/react-native-songbook) app by @matthewdorner that seems to be using abcjs along with VexFlow for rendering, and I was scratching my head over how VexFlow was even needed.  The requirement for a DOM for abcjs to render score might be the reason, and that author's workaround.  Does that seem likely?  I'll ask of course.

So ... do you think using the current abcjs in react-native is a dead end because of the DOM issue?  If not, any thoughts would be welcome.
