### ISSUE TITLE
Best way to make changes to notes

### ISSUE THREAD

**Issue by rualark** [paulrosen/abcjs#294]
What is the best way to make changes to notes when visually editing them?

- Simplest way seems to change ABC string and then run `.renderAbc`. If only one note was changed, this obviously does lots of unnecessary job, but seems robust and easy to use. Does everybody use this way? Does interactive editor also work this way? In this case we have this data flow: "internal notes representation" -> "abc string" -> "abcjs visual".
- Change only one note by some call to abcjs library and then get abc string from abcjs library if needed (I don't know if this is possible). If this is possible and preferred, should the whole tune be built like this from scratch? In this case we have this data flow: "internal notes representation" -> "abcjs visual".

P.S. Is there a way to redraw same abc string with new width, or I just need to call `.renderAbc` with new parameters?

**Comment by paulrosen** [comment]
I originally built it so that each line is independent of the others - there are a couple of things, like a slur continuation and key change hinting that affect other lines, but mostly they can be drawn separately. That was because I was worried about that very thing. But it turns out that for typical uses (a one page tune), redrawing is fast enough to not worry about it.

The interactive editor does redraw the whole thing on an edit. There is a little delay so that if you are typing fast it doesn't redraw on every character.

So many things affect everything else on a line. For instance, changing a chord from "G" to "Gm" will push everything after it to the right a little. If eighth notes are barred then changing the pitch of one changes the length of all the stems. Adding a trill above a note might move the entire staff down.

I decided worrying about it was premature optimization.

For changing the width, there are a couple of options:

1) Call renderAbc with `{ responsive: "resize" }` to take up all the width of the enclosing element.

2) Call renderAbc with `wrap: { minSpacing: 1.8, maxSpacing: 2.8, preferredMeasuresPerLine: 4 }` to move the measures to the lines where they fit best. You can experiment with the numbers to lay it out with more or less space.

3) Put `%%scale 2` and/or `%%staffwidth 400` in the ABC string.

4) query the DOM for the SVG and apply the css `transform: scale(1.5,1.5)` to it.

5) In one app I did a "scale to fit" by doing item #1, but seeing if the music is too tall, and if so, changing the width of the bounding div to cause the resizing to occur.

**Comment by paulrosen** [comment]
Oh, also, there is an intermediate step - if you have your own representation you can just convert it to the output of the parser and skip the parser step. You need to import "abcjs/test" instead of "abcjs". Then you can call:

```
var engraver_controller = new abcjs.write.EngraverController(div, {
  add_classes: true,
  staffwidth: 800,
  staffheight: 400
});

engraver_controller.engraveABC(theInternalRepresentation);
```
But, the parser doesn't take that long, so I don't think that buys you much. What takes all of the time is actually writing the SVG elements to the DOM. All other processing is insignificant for performance.

**Comment by rualark** [comment]
Thanks for detailed answer. I will try to redraw so far

**Comment by rualark** [comment]
I started to develop a visual editor. I currently have about 1 second redraw time for an average 25-measure 4-part music. Is this normal?
https://artinfuser.com/harmony/work/versions/2019-01-11.html

If most time goes to canvas drawing, are there alternative ways to draw faster? Unfortunately, I do not have experience in this field yet:
- Ignore drawing out of viewport until scrolled to?
- Using wasm?
- Drawing in 3d?

**Comment by paulrosen** [comment]
Probably not drawing if not in viewport is the best. That's not implemented, but it seems like it would be doable.

**Comment by rualark** [comment]
How about this:
1. Draw if in viewport first and return promise of full draw.
2. Continue drawing everything that is in viewport asynchronously and resolve promise.

**Comment by paulrosen** [comment]
That would have to be an option on `renderAbc` so that it is backwards compatible. But I could add it. I think that might be a bit more involved than the other issues you've brought up so I wouldn't do this first.

I need to think about the implications - like, what if the page is scrolled or if an element that is a parent of the SVG is scrolled? It has to start at the beginning to know the height of all the previous lines. I guess it would probably have to only work in the vertical direction - if the music doesn't fit horizontally it still has to render because the notes get rearranged depending on the entire line.

**Comment by rualark** [comment]
Wow. This may make symphonies renderable.

Actually, it seems to me that scrolling and moving around the page should not be handled, as it is not that robust. Most important thing seems to separate "first-class" drawing of what is in viewport and "second-class", that is out of viewport and will be drawn asynchronously.

**Comment by rualark** [comment]
Can we also split drawing into smaller blocks so that there are no delays in user interface? It could work this way:

1. Draw small portion of shapes that are in viewport. setTimeout(continueDrawing, 0);
2. Draw small portion of shapes that are in viewport. setTimeout(continueDrawing, 0);
3. Draw small portion of shapes that are in viewport. setTimeout(continueDrawing, 0);
4. Draw small portion of shapes that are in viewport. setTimeout(continueDrawing, 0);
5. Draw small portion of shapes that are out of viewport. setTimeout(continueDrawing, 0);
6. Draw small portion of shapes that are out of viewport. setTimeout(continueDrawing, 0);
7. Draw small portion of shapes that are out of viewport. setTimeout(continueDrawing, 0);
8. Draw small portion of shapes that are out of viewport. setTimeout(continueDrawing, 0);

This way we still have priority of shapes in viewport, but draw in chunks.

**Comment by paulrosen** [comment]
I'm going to tackle this soon, but first, I found some inefficiencies in the way the glyphs are rendered so I am going to improve that first since that will improve the speed for everyone.

**Comment by alexdemartos** [comment]
Hi, a related question: how did you finally modify each note after dragging it? Did you modify the ABC string and then redraw? Or is there any method we can use to transpose a single note after the dragging? Thanks in advance.

**Comment by paulrosen** [comment]
It is up to you to modify the ABC string and redraw.
