### ISSUE TITLE
Drag a note up/down

### ISSUE THREAD

**Issue by rualark** [paulrosen/abcjs#297]
Is it difficult to implement dragging a note with a mouse? I would try to do that. Currently when trying to drag a note, part names are selected.

**Comment by paulrosen** [comment]
I'm not sure what you mean by "part names are selected".

To drag, you would listen for the click and take over from there and implement your own drag-drop code. I don't think there is anything that needs to change in abcjs

**Comment by rualark** [comment]
Thanks. I'll try that.
This is how it looks when I try to drag single note so far:
![image](https://user-images.githubusercontent.com/15198808/72285353-fe02c000-3653-11ea-9b80-8cfcfe3550db.png)

**Comment by rualark** [comment]
It seems that abcjs clickListener is called on mouseup, not mousedown - so I cannot continue from there, because mouse is no longer pressed :)

Do you mean that I should listen to mouse events and forward only mousedown events to abcjs, while processing other events? In this case I need abcjs to call clickListener on mousedown.

**Comment by paulrosen** [comment]
Ah - I'll take this into consideration when I work on the note target problem.

**Comment by samuelbradshaw** [comment]
For click events, mouse-up events are usually a better user experience, because, for example, if a user starts to click something, they can decide last minute to drag their mouse away without committing. So I guess it would be good to be able to tie into both mouse-down and mouse-up. There's also a standard drag event – I don't know if that could be used in this scenario.

**Comment by paulrosen** [comment]
I've been looking at selection and dragging a little. It occurs to me that almost everything should be selectable (with the exception of the staff lines and the beams for eighth notes, maybe some other stuff) but most things shouldn't be draggable.

Notes can definitely be draggable in the vertical position (and snap to the next line/space).

It makes sense to drag notes, bars, and rests horizontally to rearrange them but the entire "event" should be selected for that. (that includes the chord, trills, etc.) But I'm not sure how that interacts with multiple voices. It might just work out fine.

However, that runs into the problem that they can't be dragged to a different line of music because that looks like dragging it vertically. Unless I see if it is on another line and change the behavior.

But those compound events should return two selections: the entire event and the piece that was selected so that the callback function can determine which part was clicked.

And it seems like this will also need an undo because it would be easy for the user to do something they didn't mean to.

**Comment by rualark** [comment]
Hi. Usually notation software does not allow horizontal dragging of notes - only vertical. Nothing can be dragged between staves.

 I am planning to implement only dragging of notes and only vertical dragging.

I will implement undo in visual editor.

**Comment by paulrosen** [comment]
I checked in an attempt at drag and drop. To run it you'll have to clone this repo and type `npm run build:basic` then use the file that is created in the `bin/` folder. Also, this is activated with a parameter so it won't have an effect unless you pass in `{ dragging: true}` in your `renderAbc` call.

(Also note that I added the parameters `{ selectionColor: "#000000", dragColor: "#000000" }`.)

I still have some debugging to do with this, but let me know if that is useful for you.

**Comment by rualark** [comment]
Thanks. Note selection color is working!

Dragging is working partially, but it is already amazing:
1. Sometimes text is selected during dragging.
2. I could not figure out how to get information about new note after dragging.
3. Trying to drag note again tries to start dragging from previous position and fails (will probably be automatically fixed after 2).

**Comment by paulrosen** [comment]
Yeah, dragging depends on the callback function causing a redraw to put the item in the new place. Otherwise the input string wouldn't match the music anymore.

If you call `renderAbc` with the `{ clickListener: callbackFunction }` the 4th parameter is the distance the note was dragged - it is in terms of steps on the music line. That is, a line to a space is 1, a line to the next line is 2. Negative moves up (sharper).

**Comment by rualark** [comment]
It works very good! Now text selection seems to be the only problem!

**Comment by rualark** [comment]
It seems that when dragging a previously selected note is not unselected. Is this possible to do?
![image](https://user-images.githubusercontent.com/15198808/72752282-d622d780-3bd2-11ea-9bce-1a377922bac4.png)

**Comment by rualark** [comment]
What browsers do you plan to support?
Currently in latest Firefox while dragging note jumps from staff up above all staves.
![image](https://user-images.githubusercontent.com/15198808/73032149-48075500-3e4f-11ea-880c-998d6f03cca5.png)

**Comment by paulrosen** [comment]
This is fixed in master, along with a few other small improvements. More coming...

**Comment by rualark** [comment]
Dragging seems unstable in Chrome / Windows 10:
https://i.imgur.com/isKrFja.gifv

**Comment by paulrosen** [comment]
Ok, will look at that. (Obviously the mouse position is returning zero sometimes - I'll try to figure out why.)

**Comment by rualark** [comment]
Not sure if selecting text was supposed to be fixed now, but when dragging pauses (and probably other elements), text is still selected:
![image](https://user-images.githubusercontent.com/15198808/74092325-28b92a80-4ad3-11ea-9d48-ae53b24fc02d.png)

**Comment by rualark** [comment]
It is impossible to drag back to pitch, where the note was before starting dragging. Is this intended behaviour?

**Comment by paulrosen** [comment]
I'm trying to balance selecting text with dragging - I'll look at it more. There should be a way to select text I just need to disable it during dragging.

The drag back to pitch sounds like a bug - will look at it.

**Comment by rualark** [comment]
After working with visual editor based on abcjs to input music I found out that selecting text is not needed, because visual editor allows to click text to edit it (and to copy). On the other hand, while working with notes, text is oftes selected accidentally, which is annoying, because it requires to click again and be more careful during editing.

I checked myself: indeed, Sibelius for example does not allow to select text by dragging and I have not heard that it is a problem.

So please, if this is not very challenging, allow to disable selecting text all together in abcjs.

**Comment by rualark** [comment]
This is an example of the problem: https://i.imgur.com/ev3zwlM.gifv
Please allow to disable text selecting.

**Comment by paulrosen** [comment]
fixed in 6.0.0-beta.13

**Comment by alexdemartos** [comment]
> Dragging seems unstable in Chrome / Windows 10:
> https://i.imgur.com/isKrFja.gifv

Hi, needless to say how grateful I am with your work. I am having similar issues in last beta-33:

https://imgur.com/a/9swudUh

Both Firefox and Chrome, so doesn't seem browser-related. Any ideas?

**Comment by Staff2Stand** [comment]
Hi, I am having the same problem on v6.2.2. Wondering if anyone was able to solve it.
