### ISSUE TITLE
Please allow to make particular element types selectable/nonselectable

### ISSUE THREAD

**Issue by rualark** [paulrosen/abcjs#354]
Currently I am looking forward to prohibit selecting of bars in simple visual editor. They are often selected when user tries to select note, which results in the need to move mouse and click again. I do not allow to change type of bar, so for this editor bars should not be selectable.

**Comment by paulrosen** [comment]
I wonder how fine grained the selection should be. Right now there is a boolean that allows you to select either everything or just notes/rests/bars.

I could either just put bars in the other category or allow an object to be passed that lets the client decide. Something like `{ notes: true, rests: true, bars: false, timeSignatures: false, keySignatures: false, clefs: false, headings: false, footers: false, slurs: false }` 

And let the client change that list without redrawing.

Is that over kill? Since this is the first real world application of this I'm not sure. I've just played with it in a few demos.

**Comment by rualark** [comment]
Hi. I think that adding separate parameter for each element type makes abcjs interface more friendly for "visual editor" usecase. Flat.io seems to be the first serious online visual editor and I believe that this type of products will experience significant development in 2020 - 2040 years due to the existing serious gap between the main offline players (Finale, Sibelius, MuseScore) and current online trend.

**Comment by paulrosen** [comment]
Ok. Look for it this weekend.

**Comment by paulrosen** [comment]
fixed in 6.0.0-beta.13
