### ISSUE TITLE
React-Native selected note not highlighted when function passed as clickedListener in parserParams

### ISSUE THREAD

**Issue by queenofthefoovultures** [paulrosen/abcjs#388]
Hi Paul! Hope you're doing well!

I'm using abcjs within a react-native app and parse the startChar and endChar with the function  "this.sendClickedNoteData" to its parent, triggered by the "clickListener". 

var ABCstring = "X:1\nT:Melody\nM:4/4\nL:1/8\nK:C\n'DDDD";

_option1:_
var abcParams = {clickListener: (abcElem) => { this.sendClickedNoteData(abcElem.startChar, abcElem.endChar) }};

_ooption2_
var abcParams = {clickListener: function(abcElem) { this.sendClickedNoteData(abcElem.startChar, abcElem.endChar)}.bind(this) };

abcjs.renderAbc("paper", ABCstring,  abcParams);

Unfortunately after the data is passed (which works) the clicked on note doesn't turn red as it would usually do. 

I Would love to hear that it is a small problem which can be solved in seconds !
Thanks for abcjs and your hard work!

Philipp

**Comment by queenofthefoovultures** [comment]
EDIT: After the data was passed I set the state of the parent, which triggered a re-render of the svg. my bad! thanks anyways!

**Comment by rpattcorner** [comment]
Philip ...
I've got a (Tune Library) React Native app in public test that renders abc sound in a webview.  This is far less than ideal, and in #578 I explored the issue with @paulrosen , eventually reaching the conclusion that it's not possible at this time because abcjs requires a DOM.

Your post suggests it's possible after all!  If that's the case, would you be willing to share a snippet of how you were able to render abc via abcjs in a react app?  Mine's a functional component oriiented Expo app, but anything will do!  It would be great to get rid of the serverside rendering.
