### ISSUE TITLE
Feature Request: Include associated note pitch value in gchord class.

### ISSUE THREAD

**Issue by santh** [paulrosen/abcjs#431]
The most useful pitch value would be the midi-note value of the note the chord applies to.

**Comment by paulrosen** [comment]
I don't quite understand what you are asking for. Can you give an example?

**Comment by santh** [comment]
Hello Paul,

I would like to be able to get the pitch of the note that a chord is “attached” to, ie. that immediately follows the <text> element that holds the chord name. When I get the abcjs_chord class elements, there is no obvious link to determine the note’s pitch except that it immediately follows it. Example:

“C7”C 

Unless I’m missing something (which is likely), there is nothing in the chord name <text> element that tells me that the pitch is “C”.

Scott



www.santhony.com <http://www.santhony.com/>
santh@comcast.net <mailto:santh@comcast.net>
650-738-2101

**Comment by paulrosen** [comment]
I see what you're asking. That will always have some weird cases - what if the chord is attached to a rest because it is syncopated? What if a chord is the second chord on a half note? What if the chords are specified with the overlay, like `G8 & "G"x2 "G#º7"x2 "A7"x2 "D7"x2 |`

I think you can probably generate the audio and study that output. I haven't tried it, but I think you have access to this:
```
var tunes = ABCJS.renderAbc( ... )
var tune = tunes[0];
var noteInfo = tune.setUpAudio(options)
```
I'm not sure if `noteInfo` will be easier to parse or not.
```

**Comment by paulrosen** [comment]
closed for inactivity
