### ISSUE TITLE
How to play a tune by new musical instrument sound?

### ISSUE THREAD

**Issue by ehsansh** [paulrosen/abcjs#643]
Hi
I do appreciate if someone could help.

I have recorded all the notes of my musical instrument which is not listed [here](http://gleitz.github.io/midi-js-soundfonts/).
I used [polyphone](https://www.polyphone-soundfonts.com/) software and convert my mp3 files to one soundfont file named ins.sf2. Could I use this file in abcjs?

I downloaded Fluid soundfonts they are just mp3, base64 files, etc. 
Is it possible to add my musical instrument to Fluid instruments? I can't understand how the program number that we set in abc string is programmed in Fluid soundfonts.

**Comment by ehsansh** [comment]
Perhaps one solution is replacing all my sound files (mp3, ogg, js, etc) with one of the Fluid instruments then use its program number in abc string. I tested this for one music note and it works. But is it a good way?

**Comment by paulrosen** [comment]
I'd love to support the sf2 format but I don't. If someone with experience with the sf2 format wants to help with this, I'd appreciate it! I mostly just need guidance.

The program number is related to the standard midi instruments (although offset by one because of the way ABC was specified). So if you look up the program names here: https://www.midi.org/specifications-old/item/gm-level-1-sound-set then you'll see, for example "violin" is program 41. That is specified in ABC as `%%MIDI program 40` and the soundfont folder contains "violin" in the name.

**Comment by ehsansh** [comment]
I would be happy to help. Unfortunately I am not experienced.
Each music note has a key in sf2 file and there should be a way to play that sound with that key number. Perhaps more complicated than my assumption. 

Thanks for the link. As my musical instrument is not in the list of midi instruments I could use those names with my own sample sounds.
