### ISSUE TITLE
abcjs in React

### ISSUE THREAD

**Issue by brianshano** [paulrosen/abcjs#741]
Are there any working examples of abcjs working in a ReactJS app?

I see react-abcjs library - https://github.com/rigobauer/react-abcjs
But it has not been updated to work with latest react version.

**Comment by paulrosen** [comment]
I don't know of any. But it should be the same as Vue:

1. add `"abcjs": "6.0.0-beta.35"` to your package.json file and `npm install`.
2. add `import abcjs from "abcjs"` to one of your files
3. put an element on the page with an id however you want (so the html is `<div id="paper">`)
4. Add the following code after the element is visible:
```
const abc = "T: Cooley's\n" +
  "M: 4/4\n" +
  "L: 1/8\n" +
  "R: reel\n" +
  "K: Emin\n" +
  "|:D2|EB{c}BA B2 EB|~B2 AB dBAG|FDAD BDAD|FDAD dAFD|\n" +
  "EBBA B2 EB|B2 AB defg|afe^c dBAF|DEFD E2:|\n" +
  "|:gf|eB B2 efge|eB B2 gedB|A2 FA DAFA|A2 FA defg|\n" +
  "eB B2 eBgB|eB B2 defg|afe^c dBAF|DEFD E2:|";

abcjs.renderAbc("paper", abc);
``` 
Let me know if there is a problem with the above instructions.

**Comment by brianshano** [comment]
That simple! 

Here it is in Codesandbox using hooks

**Comment by paulrosen** [comment]
Cool! I'm glad it worked.

I'd be happy to link to that in the help files if you'd like, or accept a pull request if you put the project in `examples/react`.

Thanks.

**Comment by brianshano** [comment]
Sure feel free to link in the help files, I'll leave it up. 
Will add the examples dir when I get a chance.

**Comment by benlieb** [comment]
It's good that this can be made to work in react using refs but it's a bit of a stretch. The major non-react-like issue is that it renders directly to the dom, and react uses a virtual dom. I've actually been prototyping a chart-building app that I'm going to make available soon built in React. https://benscharts.herokuapp.com/

I was thinking of integrating this library which I've known about for a while now, but wasn't sure it would be react-compatible enough. 

@paulrosen does abcjs use canvas or does it produce svg / or html? Can it be rendered to a string instead of a dom element directly?

**Comment by benlieb** [comment]
We've chatted a few times, a couple of years ago (https://github.com/paulrosen/abcjs/issues/243) and glad to see that you're still working on this project! Hoping to get to use it soon!

**Comment by brianshano** [comment]
Hi @benlieb 
Nice app!

I haven't found any issues using the refs to modify the dom after React has used the virtual dom. I plan on keeping it straightforward - one abc display per page and the ref specifically for the abcjs rending (which is SVG by the way).
