### ISSUE TITLE
lyrics drive dynamic marks to a wrong position 

### ISSUE THREAD

**Issue by dbq817** [paulrosen/abcjs#780]
to reproduce, see abc bellow:

```
T: demo
M: 4/4
L: 1/4
Q: 132
!mp!(c2> (3A2/c/A/|G4)!breath!|(c2- c/d/c/A/|G4)!breath!|(A>AcA)|
w:some lyrics here
```
-----------
that !mp! mark now appears up on the staff

Best regards,
Ben

**Comment by paulrosen** [comment]
That is by design so that the dynamics don't get near the lyrics. I can't remember why and I looked through the standard and the standard is quiet on where they are placed. I think I was just following other abc programs in making that decision. I'd be willing to put in a formatting command for that but I don't want to change it for existing users. I looked around and don't see one defined already, though. If you've got a suggestion, let me know.

It does look like the dynamics leaves more room than it needs to, though. I'll tighten that up in the next version.

**Comment by dbq817** [comment]
thanks Paul, 

I am not quite familiar with ABC standard actually, I will spend some time digging though.

I see some sheet music that lyrics go one line bellow the dynamics if there are, this takes more room but it looks better.

Regards,
Ben
