### ISSUE TITLE
cant change the colour of mark, or have one note a different colour

### ISSUE THREAD

**Issue by glend1** [paulrosen/abcjs#785]
im looking to change the colour of `!mark!`, but i can't seem to find anything in the documentation.

i am trying to pass some abc notation into abcjs and have one note be highlighted. i have disabled selection with `selectTypes: false` so that the user cannot change the highlighted note.

i think i would prefer to use selections, but i don't think the documentation is up to par regarding being able to select them programmatically and i haven't been able to find a way to change the colour for the selection yet either.

any pointers on how to do this would be appreciated.

**Comment by paulrosen** [comment]
I'd love to improve the docs - I'll add more info about programmatically selecting notes and also the usage of `!mark`.

You can set the style of `.abcjs-mark` to change those colors. For instance:

```
.abcjs-mark path {
  stroke: green;
  fill: green;
}
```
You could also use js to get the selector after the `renderAbc` call and modify it any way you want:
```
var el = document.getSelector(".abcjs-mark")
el.setAttribute(....)
```

If the target never changes, that is probably a good way to do it. To change the mark you'd have to redraw it if you want that colour to jump around, though.

You could put your own class on an element. If you create the music with `renderAbc(..., { add_classes: true })` then you can target a lot of stuff. See https://paulrosen.github.io/abcjs/visual/classes.html for info on how to target something. For instance if you want the second note in the fifth measure `.abcjs-mm4.abcjs-n1` will target it.

**Comment by glend1** [comment]
For me `.abcjs-mark path` did not work. `mark path` or `mark` do work. i have version 6.0.1.

Also, i'm using react which supports [css modules](https://create-react-app.dev/docs/adding-a-css-modules-stylesheet/), the implementation of setting a fixed class like this makes compatibility a little bit awkward. This means I am not able to use css modules because `.mark { ... }` is replaced with a unique-id in the css file.

**Comment by paulrosen** [comment]
Interesting. That's actually a bug that `abcjs-` was not prepended to the class name. I'll fix that, but I guess at this point I need to keep both so code doesn't break.

For the modules, what do you suggest? With Vue there is the choice to declare the css section `<style>` or `<style scoped>` and they can both be used in the same template. Therefore it is easy enough to put the abcjs styles in the former block. I can add an option to make the prefix an option, but that wouldn't help with Vue because it is implemented as added `data-v-xxxxxxxx` attributes and they aren't known to the javascript.

**Comment by glend1** [comment]
the way it works with next is that you create a `file.module.css` and then import it `import styles from ./file.module.css` into the component then, when you want to use the style in a component you would do something like `<div className={styles.myElement}></<div>`

`styles.myElement` is therefor a `string` to a uniquely identified class eg `Index_container__rpw15`. its typescript type is:

````
const styles: {
    readonly [key: string]: string;
}
````
it would appear that the construction of this class name is as follows, `[filename]_[class]__[uuid]`.

My suggestion, for flexibility and futureproofing, would be to let people define their own classes. 

there are 2 other ways next handles css. modules are optional and you can use "global" stylesheets, however there is a potential for style collision (you might want to use `.mark` elsewhere) and you can do [this](https://nextjs.org/blog/styling-next-with-styled-jsx) which is another form of global styling.

I think it is better for us to try to keep components seperate and self contained where possible to avoid compatability issues.

**Comment by paulrosen** [comment]
If you could define a prefix, would that help? That is, there are lots of classes. They all start with `.abcjs` (except for the bug you discovered above). If, instead of `{add_classes: true}` you could say `{add_classes: 'whatever`}` to prefix all the styles with whatever you put. I don't know how you'd discover the value of the uuid, though. I guess there must be a way or there wouldn't be a way to specify the class itself.

What I do in Vue is use a global stylesheet because I'm not going to use `.abcjs` as the beginning of a class value in my client code so there won't be a conflict.

Sometimes I do have different treatments for the music that appears in different places, but I manually scope that:

```
.regular-music-component {
  .abcjs-mark {
    fill: green;
  }
}
.sidebar-music-component {
  .abcjs-mark {
    fill: blue;
  }
}
```

**Comment by glend1** [comment]
no, i don't think a prefix would work, because there is also a suffix. for example, if I used `.mark` that would converted to `myfile_mark__rpw15`.

Of course, i could use regex to parse that correctly but thats not clean. I would rather use a global stylesheet.

**Comment by paulrosen** [comment]
I was wrong about `abcjs-mark` being the correct class. It is, in fact, correct for it to be `mark`.
