### ISSUE TITLE
Audio engine

### ISSUE THREAD

**Issue by elMuso** [paulrosen/abcjs#794]
Hi, I'm exploring the library and so far it's really nice.

One thing that bothers me is, the usage of external audio samples, that might not be the best for offline targeted apps like a pwa or ionic app.

Does the library provide an interface that can override the soundfont usage?

Something like a callback that gives pitch, duration and intensity so one could, for example, use webaudio oscillators or even a custom sampler implementation for the generation of (offline)audio?

If not, i think it should be a part of the library.
The roadmap looks exciting, maybe the soundfont code could be separated as a plugin so you could decide whether to use the soundfont engine or to make one yourself.

**Comment by paulrosen** [comment]
These are some interesting ideas. My first thought about oscillators is that wouldn't sound very good, but maybe for your app you only care about the pitch and not the tone.

One thing you can do immediately is use the `sequenceCallback` parameter. That will give you the exact map of what pitch sounds where. You can use that as input to your own sound generator and otherwise not use the code that loads the samples.

See the sample https://paulrosen.github.io/abcjs/examples/modify-synth-input.html and don't call `synth.prime()`, but substitute your own code.

**Comment by elMuso** [comment]
I knew there was a callback somewhere! 

Thank you for pointing me to it, as of sound quality, yes, the default oscillators are bad, but there are implementations of custom oscillators for js that can be used and improved upon, https://oscillator.js.org/ is one of them, but it has some problems (like the crackling) that I would need to fix . But using webaudio comes with the possibility of adding audio effects to somehow hide the imperfections, like a custom adsr envelope(needed to fix the crackling), reverb, flanger, chorus, etc without downloading a byte of external files (other than the script).

But the callback is a good start.

**Comment by elMuso** [comment]
In case anyone wants to do the same, i have a rough version that i will use internally. It doesn't support panning and detuning or multiple instruments but it can be a good start.
An html file is in https://gist.github.com/elMuso/2b3496c8412e5b75a31dd68b93a387be , just save it and open it in chrome, the only network resource is abcjs

The source file is in https://gist.github.com/elMuso/43834c336fa37007f91a1babaff848bb , using typescript. it can be used without abcjs as well.
