### ISSUE TITLE
TypeScript errors in index.d.ts

### ISSUE THREAD

**Issue by marcustrp** [paulrosen/abcjs#887]
Using latest npm version of abcjs, TypeScript is giving me  two errors in types/index.d.ts:

1. On this line:

`format?: { [attr: FormatAttributes]: any };`

Changing it like this makes the error go away:

`format?: { [attr in FormatAttributes]: any };`

2. RelativeElement is used as a type (in interface AbsoluteElement), but is never declared

**Comment by paulrosen** [comment]
I see the RelativeElement problem and it will be fixed in the next version.

However, I don't see the first problem. Can you add some sample code and the version of typescript you are using.

Sorry about the typescript in general. I've the retrofitting it on to the project and I'm still trying to improve it.

**Comment by marcustrp** [comment]
Tested with new npm project with abcjs 6.1.9 and typescript 4.9.5.

index.ts

`import * as abcjs from "abcjs";`

tsconfig.json

`{
  "include": ["index.ts"],
  "exclude": ["node_modules", "**/__tests__/*"]
}`

Build command for npm is just "tsc". Gives the following error:

node_modules/abcjs/types/index.d.ts:236:15 - error TS1337: An index signature parameter type cannot be a literal type or generic type. Consider using a mapped object type instead.

236   format?: { [attr: FormatAttributes]: any };

**Comment by paulrosen** [comment]
Thanks, I'll try to replicate. This should be fixed by the end of March.

**Comment by paulrosen** [comment]
Fixed in 6.2.0
