### ISSUE TITLE
Spacing between the notes?

### ISSUE THREAD

**Issue by crysfel** [paulrosen/abcjs#960]
Hi folks! Thank you for the amazing work you've been doing with this package!!

I'm currently working in an app that renders the music at a 10 scale, it looks great but it will look even better if there's a bit more space between the notes.

<img width="1768" alt="Screen Shot 2023-11-07 at 3 06 40 PM" src="https://github.com/paulrosen/abcjs/assets/219207/abe93cfa-5e51-4eb8-9ec3-f873450c02ad">

I've tried using CSS but obviously that didn't work. I'm wondering if there's another way that I can hack around this issue?

Thanks!

**Comment by paulrosen** [comment]
There are a few approaches:
1) Make the music line longer.

Put this in the header:
```
%%staffwidth 1000
```

2) Put fewer measures on each line.
```
AAee|
ffe2|
```
3) Instead of setting the scale yourself, use the attribute `{ responsive: "resize" }`. Then you won't necessarily get exactly 10x scale, but the music will fit the area provided. That is, dragging the browser window wider will make the music wider, or putting the music inside a fixed width div will let you control it. 

You can combine this with the other two options to see what works best for you.

**Comment by crysfel** [comment]
Thanks! This worked pretty great, I had actually used `staffwidth` but didn't work. This time I included the scale and it worked pretty great!!

```
const SCALE = 7
abcjs.renderAbc(musicDOM.current, TwinkleTinkle, {
  scale: SCALE,
  staffwidth: 1000 * SCALE, // <-----
  add_classes: true
});
```

Nothing happens if the value is not multiplied by the scale.

<img width="1632" alt="Screen Shot 2023-11-15 at 10 58 31 AM" src="https://github.com/paulrosen/abcjs/assets/219207/fb64136b-3dc7-4299-a4b0-e5724e6ad1f8">
